name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  rubocop:
    name: Rubocop
    runs-on: [flyci-macos-14-m2, wingman]
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1

      - name: Install dependencies
        run: bundle install

      - name: Rubocop Report
        run: rubocop --color
